name: Deploy prod

on:
  workflow_run:
    workflows: ['Run test']
    branches: [master]
    types:
      completed

jobs:
  deploy-stg:
    runs-on: ubuntu-latest

    # container:
    #   image: ruby:2.6.6

    steps:
      - uses: actions/checkout@v2

      - name: Abort the deployment if test was failed
        if: ${{ github.event.workflow_run.conclusion != 'success' }}
        run: |
          echo '::error::test was failed. exit'
          exit 1

      - name: echo ok
        run: |
          echo 'ok'
