name: Deploy

on:
  workflow_run:
    workflows:
      - Test
    branches:
      - master
      - staging
    types:
      completed

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Abort the deployment if the test failed
        if: ${{ github.event.workflow_run.conclusion != 'success' }}
        run: |
          echo "::error:: Test was failed. Abort"
          exit 1

      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.5

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install dependencies
        run: |
          sudo gem install bundler
          bundle install --jobs=4 --retry=3 --path vendor/bundle

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install awscli
        run: |
          sudo pip install awscli
          aws --version

      - name: Set aws region
        run: aws configure set region ap-northeast-1

      - name: Install ecs-deploy
        run: |
          curl https://raw.githubusercontent.com/silinternational/ecs-deploy/master/ecs-deploy | sudo tee /usr/bin/ecs-deploy
          sudo chmod +x /usr/bin/ecs-deploy

      - name: Install jq
        run: sudo apt-get install -y jq

      - run: ls -al vendor/

      - name: Deploy
        run: |
          case ${{ github.ref }} in
            'refs/heads/master' ) DEPLOY_ENV=prod ;;
            'refs/heads/staging' ) DEPLOY_ENV=stg ;;
          esac
          sudo chmod +x ./deploy.sh
          DEPLOY_ENV=${DEPLOY_ENV} ./deploy.sh
        timeout-minutes: 20
