name: Deploy

on:
  workflow_run:
    workflows:
      - Test
    branches:
      - master
      - staging
    types:
      completed

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Abort the deployment if the test failed
        if: ${{ github.event.workflow_run.conclusion != 'success' }}
        run: |
          echo "::error:: Test was failed. Abort"
          exit 1

      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.5

      - name: Install dependencies
        run: |
          sudo gem install bundler
          bundle install --jobs=4 --retry=3 --path vendor/bundle

      - name: Install deployment tools
        run: |
          # install awscli
          sudo pip install awscli
          aws configure set region ap-northeast-1

          # install ecs-deploy
          curl https://raw.githubusercontent.com/silinternational/ecs-deploy/master/ecs-deploy | sudo tee /usr/bin/ecs-deploy
          sudo chmod +x /usr/bin/ecs-deploy

          # install jq
          sudo apt-get install -y jq

      # - name: Deploy
      #   run: |
      #     case ${{ github.ref }} in
      #       'refs/heads/master' ) DEPLOY_ENV=prod ;;
      #       'refs/heads/staging' ) DEPLOY_ENV=stg ;;
      #     esac
      #     sudo chmod +x ./deploy.sh
      #     DEPLOY_ENV=${DEPLOY_ENV} ./deploy.sh
      #   timeout-minutes: 20
