name: git-commit

on:
  push:
    branches:
      - main

jobs:
  main:
    name: main
    runs-on: ubuntu-latest
    env:
      LOG_FILE_PATH: ./logs/git-commit.log
    steps:
      - name: Set date
        id: date
        run: echo "::set-output name=DATE::$(TZ=Asia/Tokyo date)"

      - uses: actions/checkout@v2
        if: ${{ env.ACT }}

      - uses: actions/checkout@v2
        if: ${{ !env.ACT }}
        with:
          ref: main

      - name: Log to file
        run: |
          echo ${{ steps.date.outputs.DATE }} >> ${{ env.LOG_FILE_PATH }}
          cat ${{ env.LOG_FILE_PATH }}

      - name: Git commit
        if: ${{ !env.ACT }}
        run: |
          git config user.name github-actions
          git config user.email github-actions.@github.com
          git add .
          git commit -m "add ${{ steps.date.outputs.DATE }}"
          git push
