name: Run rspec

on: [push]

jobs:
  rspec:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.6.6
      env:
        RAILS_ENV: test
        DATABASE_URL: mysql2://root:@mysql:3306

    services:
      mysql:
        image: mysql:5.7.18
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval 20s
          --health-timeout 10s
          --health-retries 10
        env:
          # MYSQL_DATABASE: myapp_test
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
          MYSQL_ROOT_PASSWORD: ''

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: bundle-${{ runner.os }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            bundle-${{ runner.os }}-

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs=4 --retry=3 --path vendor/bundle

      - name: Setup database
        run: |
          bundle exec rake db:create
          bundle exec rake db:schema:load

      - name: run tests
        run: |
          bundle exec rspec --profile 10 \
            --out test_results/rspec.xml \
            --format progress
